"""
Reports & Export - CardioFusion
Generate and export patient reports
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from typing import Dict
import json

def generate_text_report(prediction, patient_data, predictor=None, recommendations=None) -> str:
    """
    Generate a text-based medical report

    Args:
        prediction: Prediction results
        patient_data: Patient information
        predictor: ModelPredictor instance (optional)
        recommendations: Optional recommendations list

    Returns:
        Formatted text report
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""
================================================================================
                    CARDIO CARDIOVASCULAR RISK ASSESSMENT REPORT
================================================================================

Report Generated: {timestamp}
Patient ID: CVD-{datetime.now().strftime("%Y%m%d-%H%M%S")}

--------------------------------------------------------------------------------
PATIENT INFORMATION
--------------------------------------------------------------------------------

Demographics:
  Age Category: {patient_data.get('age_category', 'N/A')}
  Sex: {patient_data.get('sex', 'N/A')}

Physical Measurements:
  Height: {patient_data.get('height_cm', 'N/A')} cm
  Weight: {patient_data.get('weight_kg', 'N/A')} kg
  BMI: {patient_data.get('bmi', 'N/A')}

Health Status:
  General Health: {patient_data.get('general_health', 'N/A')}
  Last Checkup: {patient_data.get('checkup', 'N/A')}

Lifestyle Factors:
  Exercise: {patient_data.get('exercise', 'N/A')}
  Smoking History: {patient_data.get('smoking_history', 'N/A')}
  Alcohol Consumption: {patient_data.get('alcohol_consumption', 0)} drinks/week
  Fruit Consumption: {patient_data.get('fruit_consumption', 0)} servings/week
  Vegetable Consumption: {patient_data.get('green_vegetables_consumption', 0)} servings/week

Medical History:
  Diabetes: {patient_data.get('diabetes', 'N/A')}
  Depression: {patient_data.get('depression', 'N/A')}
  Arthritis: {patient_data.get('arthritis', 'N/A')}
  Skin Cancer: {patient_data.get('skin_cancer', 'N/A')}
  Other Cancer: {patient_data.get('other_cancer', 'N/A')}

--------------------------------------------------------------------------------
RISK ASSESSMENT RESULTS
--------------------------------------------------------------------------------

Cardiovascular Disease Risk: {prediction['risk_percentage']:.1f}%

Prediction: {prediction['prediction_label']}
Confidence Level: {prediction['confidence']*100:.1f}%
Model Used: {prediction['model']}

Risk Classification:
"""

    # Add risk category
    if predictor:
        risk_cat, emoji, _ = predictor.get_risk_category(prediction['risk_percentage'])
        report += f"  {risk_cat} {emoji}\n\n"
    else:
        # Determine risk category manually
        risk_pct = prediction['risk_percentage']
        if risk_pct < 30:
            risk_cat = "Low Risk ✅"
        elif risk_pct < 50:
            risk_cat = "Moderate-Low Risk ⚠️"
        elif risk_pct < 70:
            risk_cat = "Moderate-High Risk ⚠️"
        else:
            risk_cat = "High Risk 🚨"
        report += f"  {risk_cat}\n\n"

    # Add individual models if available
    if 'individual_models' in prediction:
        report += """
Individual Model Predictions:
"""
        for model_name, results in prediction['individual_models'].items():
            report += f"  - {model_name}: {results['probability_disease']*100:.1f}% (weight: {results['weight']:.2f})\n"

    report += """
--------------------------------------------------------------------------------
CLINICAL RECOMMENDATIONS
--------------------------------------------------------------------------------
"""

    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            report += f"{i}. {rec}\n"
    else:
        report += """
1. Consult with your healthcare provider for personalized medical advice
2. Follow a heart-healthy diet (Mediterranean style recommended)
3. Engage in regular physical activity (150 minutes/week minimum)
4. Monitor blood pressure and cholesterol levels regularly
5. Maintain a healthy weight (BMI 18.5-25)
"""

    report += f"""
--------------------------------------------------------------------------------
IMPORTANT DISCLAIMER
--------------------------------------------------------------------------------

This report is generated by CardioFusion, an AI-powered cardiovascular disease
risk assessment tool. This tool is for educational and informational purposes
only and does NOT provide medical advice, diagnosis, or treatment.

ALWAYS seek the advice of your physician or other qualified health provider
with any questions you may have regarding a medical condition. Never disregard
professional medical advice or delay in seeking it because of something you
have read in this report.

The predictions made by this tool are based on machine learning models trained
on historical data and may not be applicable to your specific situation. Only
a qualified healthcare provider can provide personalized medical advice.

--------------------------------------------------------------------------------
END OF REPORT
--------------------------------------------------------------------------------

Generated by CardioFusion v1.0.0
For questions or concerns, please consult with a healthcare professional.

© 2024 CardioFusion Development Team. All rights reserved.
================================================================================
"""

    return report


def render_reports_page(prediction, patient_data, input_data, predictor):
    """Render reports and export page"""

    st.markdown("## 📄 Reports & Export")
    st.markdown("**Generate and download your risk assessment report**")

    st.divider()

    # Report preview
    st.markdown("### 📋 Report Preview")

    tab1, tab2, tab3 = st.tabs(["Summary Report", "Detailed Analysis", "Export Options"])

    with tab1:
        # Generate report
        report_text = generate_text_report(prediction, patient_data)

        st.text_area(
            "Medical Report",
            value=report_text,
            height=600,
            disabled=True
        )

        # Download button
        st.download_button(
            label="📥 Download Text Report (.txt)",
            data=report_text,
            file_name=f"cardio_risk_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            type="primary"
        )

    with tab2:
        st.markdown("#### Detailed Assessment Data")

        # Create detailed data export
        detailed_data = {
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'patient_data': patient_data,
            'prediction_results': {
                'risk_percentage': prediction['risk_percentage'],
                'prediction_label': prediction['prediction_label'],
                'confidence': prediction['confidence'],
                'model': prediction['model']
            }
        }

        if 'individual_models' in prediction:
            detailed_data['individual_models'] = prediction['individual_models']

        # Display as JSON
        st.json(detailed_data)

        # Download JSON
        json_str = json.dumps(detailed_data, indent=2)
        st.download_button(
            label="📥 Download Detailed Data (JSON)",
            data=json_str,
            file_name=f"cardio_assessment_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
            mime="application/json"
        )

    with tab3:
        st.markdown("#### Export Options")

        st.info("""
        **Available Export Formats:**
        - ✅ **Text Report (.txt)** - Ready to download
        - ✅ **JSON Data (.json)** - Machine-readable format
        - 🔜 **PDF Report (.pdf)** - Coming soon
        - 🔜 **CSV Data (.csv)** - Coming soon
        """)

        st.markdown("---")

        # Email/Share options (placeholder)
        st.markdown("#### Share Report")

        email = st.text_input("Email address (optional)", placeholder="your.doctor@example.com")

        if st.button("📧 Email Report", disabled=True):
            st.warning("Email functionality coming soon!")

        st.caption("💡 For now, you can download the report and email it manually to your healthcare provider.")

    st.divider()

    # Report history (placeholder for future feature)
    st.markdown("### 📊 Assessment History")

    st.info("""
    **Track Your Progress Over Time**

    Future feature: Save your assessments and track how your risk changes as you make
    lifestyle improvements. Coming soon!

    For now, save your downloaded reports in a folder to track manually.
    """)

    # Sample history visualization (placeholder)
    if st.checkbox("Preview History Feature", value=False):
        # Mock data for demonstration
        history_data = {
            'Date': ['2024-01-15', '2024-02-15', '2024-03-15'],
            'Risk %': [78, 72, 65],
            'BMI': [32, 30, 28],
            'Exercise': ['No', 'Sometimes', 'Yes']
        }

        df = pd.DataFrame(history_data)
        st.line_chart(df.set_index('Date')['Risk %'])

        st.caption("This is a preview of upcoming history tracking feature")
